### ISSUE TITLE
Graphical Error

### ISSUE THREAD

**Issue by Trollbooty** [Luxocracy/NeatPlates#206]
Hello! I've had this problem for a week now. A random health plate of a nearby ally or npc will cover my own character's default blizzard health plate. 
![WoWScrnShot_041820_013901](https://user-images.githubusercontent.com/55899508/79937739-f0f62980-8417-11ea-9d77-e0d7cc44ff5a.jpg)
![WoWScrnShot_041820_013904](https://user-images.githubusercontent.com/55899508/79937746-f3f11a00-8417-11ea-8807-bcc5320cb623.jpg)
![WoWScrnShot_041820_013907](https://user-images.githubusercontent.com/55899508/79937764-fb182800-8417-11ea-866f-4065d4e768b4.jpg)

**Comment by Luxocracy** [comment]
Sorry for not having responded to this, kinda just forgot after thinking I'll take a look at it later.

My best guess at what could cause this is if the event for removing a nameplate doesn't get fired for some reason by the game. Which causes some data not to get removed from the nameplate as intended and then your own personal plate, which is normally ignored by the addon, still has this data and it doesn't get overwritten by new data. Because I can achieve similar results when I disable that function, although not exactly the same.

But anyways, I've released a new version that adds some checks to if a nameplate should actually be displayed or not instead of relying entirely on that event to happen. So hopefully that fixes the issue, but it might not.

**Comment by Trollbooty** [comment]
I'm still having this issue, perhaps, there is an option I can turn off?

**Comment by Luxocracy** [comment]
I've got one more idea I can try that I've added to the latest release, but if that doesn't resolve your issue I'd be looking at what other addons you have that might affect nameplates in some fashion as it is quite likely a conflict of some sorts happening.

**Comment by Trollbooty** [comment]
Still have the issue. What addons do you think it could be, if any?

**Comment by Luxocracy** [comment]
It's hard to say, but pretty much anything that interact with nameplates.

But is there anything specifically that makes this happen? And could you export and post your profile settings, so I can rule out it being settings related.

**Comment by Trollbooty** [comment]
Sorry for the delay.  A random question, is there a way to change the bars of pets, minions, and guardians?




^1^T^STextShowOnlyOnActive^b^SWidgetAuraSort^N1^SUnitSpotlightLookup^T^t^SEnableOffTankHighlight^b^SSpellCastEnableFriendly^b^SWidgetPandemic^b^SStyleEnemyBarsInstanceMode^b^SFriendlyNameColorMode^SDefault^SHighlightMouseoverScale^T^Sy^N1^Sx^N1^Soffset^T^Sy^N0^Sx^N0^t^t^SColorEnemyStatusTextMode^N1^SOpacityNonTarget^N0.97^SStyleEnemyBarsOnElite^B^SStyleEnemyBarsNoTotem^b^SIntCastWhoEnable^b^SUnitSpotlightColor^T^Sr^N0.8^Sg^N0^Sb^N0^t^SStyleEnemyBarsClickThrough^b^SStyleFriendlyBarsClickThrough^b^SStatusTextRight^N7^SStyleFriendlyBarsOnPlayers^B^SWidgetAuraTrackCurse^B^SWidgetQuestIcon^b^SStatusTextCenterColor^B^SColorFriendlyNameMode^N1^SColorBuffPurgeable^T^Sa^F9007179390517248^f-53^Sr^N0^Sg^F4521250869215232^f-53^Sb^F9007179390517248^f-53^t^SHighlightTargetMode^N1^SHeadlineFriendlySubtext^SPercentHealth^SWidgetBuffPurgeable^b^SWidgetThreatIndicator^b^SHeadlineEnemyColor^N4^SWidgetAuraScaleOptions^T^Sy^N1^Sx^N1^Soffset^T^Sy^N0^Sx^N0^t^t^SColorRangeClose^T^Sa^F9007179390517248^f-53^Sr^F7912188752691200^f-57^Sg^F7876866941648896^f-53^Sb^F7417676955648000^f-53^t^SClassPartyIcon^b^SColorHostilePlayer^T^Sa^F9007179390517248^f-53^Sr^F9007179390517248^f-53^Sg^N0^Sb^N0^t^SWidgetRangeScaleOptions^T^Sy^N1^Sx^N1^Soffset^T^Sy^N0^Sx^N0^t^t^SStatusTextRightColor^B^SWidgetsComboPoints^B^SSpacerSlots^N0^SOpacityFilterFriendlyPlayers^b^SEmphasizedAuraList^S^SStyleFriendlyBarsOnElite^B^SCastBarWidth^N1^SStyleFriendlyBarsOnActive^B^SFriendlyBarColorMode^SByReaction^SColorRangeFar^T^Sa^F9007179390517248^f-53^Sr^F9007179390517248^f-53^Sg^F4521250869215232^f-53^Sb^N0^t^STextShowLevel^b^SHeadlineEnemySubtext^SPercentHealth^STextColorPartyMember^T^Sa^F9007179390517248^f-53^Sr^F8477345245560832^f-55^Sg^F5934141564518400^f-53^Sb^F9007179390517248^f-53^t^SUnitSpotlightGlowEnable^B^SWidgetAuraTrackDisease^B^SStyleForceBarsOnTargets^b^SColorMouseover^T^Sa^F9007179390517248^f-53^Sr^F7770899897909248^f-54^Sg^F7770899897909248^f-54^Sb^F7770899897909248^f-54^t^SWidgetDebuff^B^SUnitSpotlightScaleEnable^B^SColorPartyAggroText^b^SScaleFiltered^N0.82^SScaleTargetSpotlight^B^SOpacitySpotlightMouseover^b^SOpacityFilterInactive^b^SWidgetRangeUnits^N2^SStyleEnemyBarsOnNPC^B^SWidgetsEnableExternal^B^SWidgetsThreatIndicator^B^SStyleFriendlyMode^N2^SAdvancedEnableUnitCache^B^SHighlightMouseoverMode^N1^SOpacityFilterNeutralUnits^b^STextColorFriendlyNPC^T^Sa^F9007179390517248^f-53^Sr^F5828175057649664^f-53^Sg^F7594288695214080^f-53^Sb^F7912188752691200^f-53^t^SOpacityFilterEnemyNPC^b^STextNameColorMode^N1^SClassEnemyIcon^b^SOpacityTarget^N0.64^SStyleShowPowerBar^b^STextColorHostilePlayer^T^Sa^F9007179390517248^f-53^Sr^F9007179390517248^f-53^Sg^F7205743405039616^f-55^Sb^F4521250869215232^f-55^t^SWidgetAuraTrackPoison^B^SWidgetTotemIcon^b^SColorTapped^T^Sa^F9007179390517248^f-53^Sr^F7770899897909248^f-54^Sg^F7770899897909248^f-54^Sb^F7770899897909248^f-54^t^SSpellCastEnableEnemy^B^SWidgetAbsorbMode^N1^SWidgetAllAuras^b^SWidgetRangeScale^b^SWidgetOffsetY^N0^SColorFriendlyPlayer^T^Sa^F9007179390517248^f-53^Sr^N0^Sg^F7205743405039616^f-55^Sb^F9007179390517248^f-53^t^SColorPartyAggroGlow^b^SEmphasizedAuraPriority^T^t^SScaleSpotlightMode^N2^SWidgetEliteIndicator^B^SIntCastEnable^b^SAuraScale^N1^SColorThreatTransition^T^Sa^F9007179390517248^f-53^Sr^F9007179390517248^f-53^Sg^F5651563854954496^f-53^Sb^N0^t^SFriendlyHeadlineColor^SByReaction^SEnemyHeadlineColor^SByReaction^SScaleSpotlight^N1.37^SCastbarDurationMode^SNone^SColorFocus^T^Sa^F9007179390517248^f-53^Sr^F7770899897909248^f-54^Sg^F7770899897909248^f-54^Sb^F7770899897909248^f-54^t^STextColorBoss^T^Sa^F7205743405039616^f-53^Sr^F9007179390517248^f-53^Sg^F7664932854169600^f-53^Sb^F7347032796692480^f-56^t^SUnitSpotlightOpacityEnable^B^SScaleCastingSpotlight^B^SStatusTextCenter^N5^SColorFriendlyBarMode^N1^SScaleIgnoreNeutralUnits^b^SWidgetsDebuff^B^SBorderBuffEnrage^N1^SOpacityFilterNonElite^b^STheme^SNeon^SFriendlySubtext^SNone^SOpacityFilterPlayers^b^SColorFriendlyStatusTextMode^N1^SColorTarget^T^Sa^F9007179390517248^f-53^Sr^F7770899897909248^f-54^Sg^F7770899897909248^f-54^Sb^F7770899897909248^f-54^t^SColorThreatWarning^T^Sa^F9007179390517248^f-53^Sr^F7205743405039616^f-53^Sg^N0^Sb^N0^t^SWidgetRangeMode^N1^SStyleFriendlyBarsNoTotem^b^SColorRangeOOR^T^Sa^F9007179390517248^f-53^Sr^F8124122840170496^f-53^Sg^F7912188752691200^f-57^Sb^F5368985608519680^f-56^t^SWidgetsComboPointsStyle^N2^SOpacityFilterFriendlyNPC^b^SColorRangeMelee^T^Sa^N0^Sr^F8124122840170496^f-53^Sg^F8124122840170496^f-53^Sb^F8124122840170496^f-53^t^SWidgetComboPointsStyle^N2^SHideAuraInHeadline^b^SFrameVerticalPosition^N0.7^SHighlightFocustMode^N1^SCustomColorList^S^SWidgetEnableExternal^B^SWidgetsDebuffTrackList^SMy~`Agony~JMy~`Corruption~JMy~`Unstable~`Affliction~JMy~`Haunt~JMy~`Fear~JMy~`Blood~`Horror~JMy~`Shadowfury~JAll~`Kidney~`Shot~JAll~`Sheep~JAll~`Cyclone~JMy~`Immolate~JMy~`Conflagrate~JMy~`Havoc~JMy~`~`Hamstring~JMy~`Mortal~`Wounds~JMy~`~`Rend~JMy~`~`Storm~`Bolt~JMy~`Intimidating~`Shout~JMy~`Thunder~`Clap~JMy~`Colossus~`Smash~JMy~`Shockwave~JMy~`Earth~`Shield^STextColorGuildMember^T^Sa^F9007179390517248^f-53^Sr^F8477345245560832^f-55^Sg^F5934141564518400^f-53^Sb^F9007179390517248^f-53^t^SStyleEnemyMode^N1^SColorPartyAggro^T^Sa^F9007179390517248^f-53^Sr^F9007179390517248^f-53^Sg^N0^Sb^F7205743405039616^f-54^t^SOpacityFilterLookup^T^SFanged~`Pit~`Viper^B^SSearing~`Flame~`Totem^B^SSearing~`Totem^B^SEbon~`Gargoyle^B^SWild~`Imp^B^SSpirit~`Wolf^B^SArmy~`of~`the~`Dead~`^B^SFire~`Elemental~`Totem^B^SArmy~`of~`the~`Dead^B^SMirror~`Images^B^SEarthgrab~`Totem^B^t^STextColorNeutral^T^Sa^F9007179390517248^f-53^Sr^F8901212883648512^f-53^Sg^F6358009202606080^f-53^Sb^F7629611043127296^f-56^t^SColorEnemyNameMode^N1^SColorFriendlyNPC^T^Sa^F9007179390517248^f-53^Sr^F8194766999126016^f-56^Sg^F9007179390517248^f-53^Sb^N0^t^SWidgetAuraTrackMagic^B^SScaleMouseoverSpotlight^b^STextColorFriendlyPlayer^T^Sa^F9007179390517248^f-53^Sr^F6216719810953216^f-57^Sg^F5792852709736448^f-53^Sb^F9007179390517248^f-53^t^SEnemyBarColorMode^SByClass^SOpacityFullNoTarget^B^SColorHighHealth^T^Sa^F9007179390517248^f-53^Sr^N0^Sg^F9007179390517248^f-53^Sb^F7205743405039616^f-55^t^SStyleHeadlineMiniMobs^b^SHeadlineFriendlyColor^N4^SWidgetsDebuffPriority^T^SCorruption^N2^SShadowfury^N7^SBlood~`Horror^N6^SSheep^N9^SRend^N16^SImmolate^N11^SConflagrate^N12^SAgony^N1^SThunder~`Clap^N19^SHaunt^N4^SFear^N5^SHamstring^N14^SStorm~`Bolt^N17^SUnstable~`Affliction^N3^SEarth~`Shield^N22^SMortal~`Wounds^N15^SHavoc^N13^SKidney~`Shot^N8^SIntimidating~`Shout^N18^SColossus~`Smash^N20^SShockwave^N21^SCyclone^N10^t^SWidgetDebuffPriority^T^t^SOpacityFilterList^SFanged~`Pit~`Viper~JSearing~`Totem~JSearing~`Flame~`Totem~JEbon~`Gargoyle~JArmy~`of~`the~`Dead~JFire~`Elemental~`Totem~JSpirit~`Wolf~JArmy~`of~`the~`Dead~`~JMirror~`Images~JWild~`Imp~JEarthgrab~`Totem^SStyleFriendlyBarsNoMinions^b^SColorHealthBarMode^N3^STextShowUnitTitle^b^SColorHostileNPC^T^Sa^F9007179390517248^f-53^Sr^F9007179390517248^f-53^Sg^N0^Sb^N0^t^SThreatGlowEnable^b^SStyleEnemyBarsOnActive^B^SColorGuildMember^T^Sa^F9007179390517248^f-53^Sr^F8477345245560832^f-55^Sg^F5934141564518400^f-53^Sb^F9007179390517248^f-53^t^SClassColorPartyMembers^b^SThreatWarningMode^SAuto^SEmphasizedUnique^b^SHighHealthThreshold^N0.7^SOpacityFilterEnemyPlayers^b^SHideCooldownSpiral^b^SWidgetAuraAlignment^N1^SUnitSpotlightList^S^SBorderPandemic^N1^SCustomMouseoverColor^b^SColorShowPartyAggro^b^SEnemyAlphaSpotlightMode^SByThreat^SOpacitySpotlightRaidMarked^b^SFocusAsTarget^b^SWidgetsDebuffStyle^N2^SColorBuffEnrage^T^Sa^F9007179390517248^f-53^Sr^N0^Sg^F4521250869215232^f-53^Sb^F9007179390517248^f-53^t^SWidgetThreatPercentage^b^STextHealthTextMode^N1^SPreciseAuraThreshold^N10^SOpacityFilterPartyMembers^b^SWidgetRangeIndicator^b^SWidgetOffsetX^N0^SEnemyStatusTextMode^SHealthFunctionPercent^SWidgetMyDebuff^B^SColorUnIntpellCast^T^Sa^F9007179390517248^f-53^Sr^F8547989941387264^f-54^Sg^F6287364506779648^f-53^Sb^F6887843347562496^f-53^t^SOpacityFilterEnemyPet^b^SFrameBarWidth^N1^SStyleHeadlineNeutral^b^SCustomization^T^SNameOnly^T^t^SDefault^T^t^SWidgetConfig^T^t^t^SColorLowHealth^T^Sa^F9007179390517248^f-53^Sr^F9007179390517248^f-53^Sg^F6499298057388032^f-56^Sb^F5651563854954496^f-58^t^SCustomColorLookup^T^t^SColorThreatSafe^T^Sa^F9007179390517248^f-53^Sr^F8477345245560832^f-57^Sg^F5298340912693248^f-53^Sb^F8124122840170496^f-53^t^SWidgetDebuffStyle^N1^SCustomTargetColor^b^SHideAuraDuration^b^SWidgetsTotemIcon^b^SOpacityFilterMini^B^SOpacityFilterNonPartyMembers^b^SEmphasizedAuraLookup^T^t^SStatusTextLeft^N8^SWidgetsDebuffLookup^T^SCorruption^N2^SShadowfury^N2^SBlood~`Horror^N2^SSheep^N1^SRend^N2^SImmolate^N2^SConflagrate^N2^SAgony^N2^SThunder~`Clap^N2^SHaunt^N2^SFear^N2^SHamstring^N2^SStorm~`Bolt^N2^SUnstable~`Affliction^N2^SEarth~`Shield^N2^SMortal~`Wounds^N2^SHavoc^N2^SKidney~`Shot^N1^SIntimidating~`Shout^N2^SColossus~`Smash^N2^SShockwave^N2^SCyclone^N1^t^SWidgetMaxRange^N40^SOpacityFilterLowLevelUnits^b^SSpellIconEnable^B^SEnemyNameColorMode^SDefault^SWidgetComboPoints^b^SColorMediumHealth^T^Sa^F9007179390517248^f-53^Sr^F9007179390517248^f-53^Sg^F9007179390517248^f-53^Sb^N0^t^SWidgetsMyBuff^B^SWidgetDebuffTrackList^S^SStyleFriendlyBarsInstanceMode^b^SOpacityFiltered^N0^SOpacitySpotlight^N1^SWidgetBuffEnrage^b^SWidgetBuffFilter^N1^SStatusTextLeftColor^B^SUnitSpotlightOpacity^N1^STextColorHostileNPC^T^Sa^F9007179390517248^f-53^Sr^F9007179390517248^f-53^Sg^F7205743405039616^f-55^Sb^F4521250869215232^f-55^t^SWidgetTargetHighlight^B^STextShowServerIndicator^B^SUnitSpotlightScale^N1.4^SScaleIgnoreNonEliteUnits^b^SWidgetRangeMax^N40^STextUseBlizzardFont^B^SOpacityFilterUntitledFriendlyNPC^b^SColorAttackingOtherTank^T^Sa^F9007179390517248^f-53^Sr^F8477345245560832^f-57^Sg^F6004786260344832^f-53^Sb^F7064454550257664^f-53^t^SStyleEnemyBarsOnPlayers^B^SScaleIgnoreInactive^b^SStyleHeadlineOutOfCombat^b^SColorNeutral^T^Sa^F9007179390517248^f-53^Sr^F9007179390517248^f-53^Sg^F9007179390517248^f-53^Sb^N0^t^SWidgetAuraTrackDispelFriendly^b^SHighlightFocusScale^T^Sy^N1^Sx^N1^Soffset^T^Sy^N0^Sx^N0^t^t^SHighlightTargetScale^T^Sy^N1^Sx^N1^Soffset^T^Sy^N0^Sx^N0^t^t^SOpacitySpotlightSpell^b^STextStatusForceShadow^b^SWidgetAbsorbUnits^N1^SColorEnemyBarMode^N1^SClassIconScaleOptions^T^Sy^N1^Sx^N1^Soffset^T^Sy^N0^Sx^N0^t^t^SWidgetMyBuff^b^SScaleStandard^N1^SWidgetsRangeMode^N1^SStyleEnemyBarsNoMinions^b^SFriendlyAlphaSpotlightMode^SNone^STextColorElite^T^Sa^F4521250869215232^f-53^Sr^F8124122840170496^f-53^Sg^F6322686854692864^f-53^Sb^F5439629767475200^f-54^t^SWidgetComboPointsScaleOptions^T^Sy^N1^Sx^N1^Soffset^T^Sy^N0^Sx^N0^t^t^SColorDangerGlowMode^N2^SAltShortening^b^SCustomFocusColor^b^SFriendlyStatusTextMode^SHealthFunctionPercent^SWidgetAbsorbIndicator^b^SColorNormalSpellCast^T^Sa^F9007179390517248^f-53^Sr^F8901212883648512^f-53^Sg^F4945117970432000^f-53^Sb^N0^t^SLowHealthThreshold^N0.3^SHighlightFocusMode^N1^SScaleFunctionMode^SByThreat^STextColorNormal^T^Sa^F7205743405039616^f-54^Sr^F5863497405562880^f-53^Sg^F5863497405562880^f-53^Sb^F5863497405562880^f-53^t^SColorIntpellCast^T^Sa^F9007179390517248^f-53^Sr^N0^Sg^F4521250869215232^f-53^Sb^F9007179390517248^f-53^t^SWidgetDebuffLookup^T^t^SBorderBuffPurgeable^N1^SColorPandemic^T^Sa^F9007179390517248^f-53^Sr^N0^Sg^F4521250869215232^f-53^Sb^F9007179390517248^f-53^t^SUseGlobalSet^b^SColorPartyMember^T^Sa^F9007179390517248^f-53^Sr^F8477345245560832^f-55^Sg^F5934141564518400^f-53^Sb^F9007179390517248^f-53^t^SWidgetsRangeIndicator^b^SColorRangeMid^T^Sa^F9007179390517248^f-53^Sr^F5086407362084864^f-57^Sg^F7806222245822464^f-53^Sb^N0^t^SFilterScaleLock^B^SEmphasizedSlots^N1^SWidgetsMyDebuff^B^SWidgetDebuffFilter^N2^SEnemySubtext^SNone^SThreatMode^N1^SUnitSpotlightBarEnable^B^SWidgetRangeStyle^N1^STextShowOnlyOnTargets^b^SStyleFriendlyBarsOnNPC^B^SColorPartyAggroBar^b^SOpacityFilterFriendlyPet^b^t^^

**Comment by Luxocracy** [comment]
What do you mean by change? If you want them to look different it's very limited to things such as scale, opacity or headline view.

**Comment by Trollbooty** [comment]
Yes, those options it self. What would it be under? And I hope that was the right thing to import.

**Comment by Luxocracy** [comment]
It would have to be done through the _Unit Filter_ system in the profile settings. And yes that was the correct export for profile.

**Comment by Trollbooty** [comment]
Any update on this?

**Comment by Trollbooty** [comment]
It must be an addon on my end?

**Comment by Luxocracy** [comment]
It's possible that it's due to some interaction with another addon. Especially if there's an addon that also interacts with the nameplates in some way. 

As what appears to happen is that the old nameplate, as they get reused, doesn't get hidden, or gets re-shown, when it changes to your personal nameplate.

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
